config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  get 'game_day', to: 'game_day#index', as: 'game_day'
  get 'drafts/:draft_id/picks', to: 'drafts#picks', as: 'draft_picks'
  get 'rules', to: 'rules#index', as: 'rules'
  get 'admin', to: 'admin#index', as: 'admin'

  get 'second_chance_votes/get_data', to: 'second_chance_votes#get_data',
      as: 'second_chance_votes_get_data'

  get 'second_chance_votes/results', to: 'second_chance_votes#results',
      as: 'second_chance_votes_results'

  resources :seasons, :episodes, :castaways, :drafts, :tribes, :users,
            :vote_outs, :second_chance_votes, :rule_articles, :admin_episodes,
            :admin_castaways, :admin_seasons, :admin_tribes

  resources :late_picks, only: %w(new create)

end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  number      :integer
#  season_id   :integer
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  air_date    :date
#

class Episode < ActiveRecord::Base

  belongs_to :season
  has_many :chat_messages
  has_one :vote_out

  def knocked_out
    if vote_out
      User.who_picked(vote_out.contestant).select { |x|
        # get the users picks
        x.picks.where(pick_type: 'cash').select { |y|
          # check to see if voted out
          y.contestant.vote_outs.length >= 1
        }.length == 2
      }
    else
      []
    end
  end

  def as_json(options={})
    {
        name: name,
        won_reward: 2,
        won_immunity: 1,
        voted_out: 3,
        season: season.id,
        notes: 'Kyle Rules'
    }
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  # before_action :authenticate_user!

  def index
    @episodes = Episode.all
    @episodes = @episodes.where(season_id: params[:season]) if params[:season]
    respond_to do |format|
      format.html
      format.json { render json: @episodes }
    end
  end

  def show
    @episode = Episode.find(params[:id])
  end

  def edit
    @episode = Episode.find(params[:id])
    render layout: 'center_form'
  end

  def new
    render layout: 'center_form'
  end

  def create
    Episode.create!(episode_params)
    redirect_to episodes_path
  end

  def update
    @episode = Episode.find(params[:id])
    @episode.update! episode_params
    redirect_to episode_path(@episode)
  end

  private

  def episode_params
    params.require(:episode).permit(:number, :name, :air_date,
                                    :season_id, :description)
  end
end

app/views/episodes/edit.html.erb
<%= form_for @episode, :layout => :basic do |f| %>
  <%= f.number_field :number %>
  <%= f.text_field :name %>
  <%= f.select :season_id do %>
    <% Season.all.each do |s| %>
      <%= content_tag(:option, s.name, :value => s.id) %>
    <% end %>
  <% end %>
  <%= f.date_field :air_date %>
  <%= f.text_area :description %>
  <%= f.submit 'Update' %>
<% end %>

app/views/episodes/index.html.erb
<h1>
  Episodes
  <span class="pull-right">
    <%#= link_to 'New', new_episode_path,
                class: 'btn btn-primary btn-sm' if current_user.admin? %>
  </span>
</h1>

<hr/>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th class="col-xs-2">Name</th>
      <th>Voted Out</th>
      <th class="col-xs-1">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @episodes.each do |e| %>
      <tr>
        <td><%= link_to e.name, episode_path(e) %></td>
        <td><%= e.vote_out.try(:contestant).try(:name) %></td>
        <td>
          <%#= link_to 'Edit', edit_episode_path(e),
                      class: 'btn btn-primary btn-xs' if current_user.admin? %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/episodes/new.html.erb
<h1 class="text-center">New Episode</h1>
<%= form_for Episode.new, :action => :create, :layout => :basic do |f| %>
  <%= f.number_field :number %>
  <%= f.text_field :name %>
  <%= f.select :season_id do %>
    <% Season.all.each do |s| %>
      <%= content_tag(:option, s.name, value: s.id) %>
    <% end %>
  <% end %>
  <%= f.date_field :air_date %>
  <%= f.text_area :description %>
  <%= f.submit 'Save' %>
<% end %>

app/views/episodes/show.html.erb
<h1>
  <div class="row">
    <div class="col-sm-6 col-xs-10 textfill">
      <span><%= @episode.name %></span>
    </div>
    <div class="col-sm-5 hidden-xs textfill">
        <span><%= @episode.season.try(:name) %></span>
    </div>
    <div class="col-sm-1 col-xs-2 text-right">
      <%= link_to 'Edit', edit_episode_path(@episode),
                  class: 'btn btn-primary btn-sm' if current_user.admin? %>
    </div>
  </div>
</h1>
<hr/>
<%= panel_row :column_class => 'col-sm-6 col-xs-12' do %>
  <%= panel :heading => 'Contestants', :context => :success do %>
    <p><%= icon :user %> <%= @episode.vote_out.try(:contestant).try(:name) %></p>
  <% end %>
  <%= panel :heading => 'Pool Players', :context => :warning do %>
    <% @episode.knocked_out.each do |k| %>
      <p><%= icon :flash %> <%= k.try(:name) %></p>
    <% end %>
  <% end %>
<% end %>