config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  get 'game_day', to: 'game_day#index', as: 'game_day'
  get 'drafts/:draft_id/picks', to: 'drafts#picks', as: 'draft_picks'
  get 'rules', to: 'rules#index', as: 'rules'
  get 'admin', to: 'admin#index', as: 'admin'

  get 'second_chance_votes/get_data', to: 'second_chance_votes#get_data',
      as: 'second_chance_votes_get_data'

  get 'second_chance_votes/results', to: 'second_chance_votes#results',
      as: 'second_chance_votes_results'

  resources :seasons, :episodes, :castaways, :drafts, :tribes, :users,
            :vote_outs, :second_chance_votes, :rule_articles, :admin_episodes,
            :admin_castaways, :admin_seasons, :admin_tribes

  resources :late_picks, only: %w(new create)

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'nonavbar'
  def index
    @show_spoilers = current_user.try(:show_spoilers)
    @recent_vote_outs = VoteOut.all.reverse_order[0..2]

    if current_user
      redirect_to game_day_path
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="text-center col-xs-12 col-sm-8 col-sm-offset-2">
    <%= image_tag 'Survivor Club Logo (Cambodia Edition).png', class: 'img-responsive center-block' %>
    <h1>Welcome to Survivor Club</h1>
    <%= nav layout: :justified, class: 'welcome-nav' do %>
      <%= link_to 'Rules', rules_path %>
      <%= link_to 'Episodes', episodes_path %>
      <%= link_to 'Castaways', castaways_path %>
      <%= link_to 'Players', users_path %>
      <%= link_to 'Log In', new_user_session_path %>
    <% end %>
</div>