config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  get 'game_day', to: 'game_day#index', as: 'game_day'
  get 'drafts/:draft_id/picks', to: 'drafts#picks', as: 'draft_picks'
  get 'rules', to: 'rules#index', as: 'rules'
  get 'admin', to: 'admin#index', as: 'admin'

  get 'second_chance_votes/get_data', to: 'second_chance_votes#get_data',
      as: 'second_chance_votes_get_data'

  get 'second_chance_votes/results', to: 'second_chance_votes#results',
      as: 'second_chance_votes_results'

  resources :seasons, :episodes, :castaways, :drafts, :tribes, :users,
            :vote_outs, :second_chance_votes, :rule_articles, :admin_episodes,
            :admin_castaways, :admin_seasons, :admin_tribes

  resources :late_picks, only: %w(new create)

end

app/controllers/admin_episodes_controller.rb
class AdminEpisodesController < ApplicationController
  before_action :set_admin_episode, only: [:show, :edit, :update, :destroy]

  # GET /admin_episodes
  # GET /admin_episodes.json
  def index
    @admin_episodes = Episode.all
  end

  # GET /admin_episodes/1
  # GET /admin_episodes/1.json
  def show
  end

  # GET /admin_episodes/new
  def new
    @admin_episode = Episode.new
  end

  # GET /admin_episodes/1/edit
  def edit
  end

  # POST /admin_episodes
  # POST /admin_episodes.json
  def create
    @admin_episode = Episode.new(admin_episode_params)

    respond_to do |format|
      if @admin_episode.save
        format.html { redirect_to admin_episodes_path, notice: 'Admin episode was successfully created.' }
        format.json { render :show, status: :created, location: @admin_episode }
      else
        format.html { render :new }
        format.json { render json: @admin_episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_episodes/1
  # PATCH/PUT /admin_episodes/1.json
  def update
    respond_to do |format|
      if @admin_episode.update(admin_episode_params)
        format.html { redirect_to admin_episodes_path, notice: 'Admin episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_episode }
      else
        format.html { render :edit }
        format.json { render json: @admin_episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_episodes/1
  # DELETE /admin_episodes/1.json
  def destroy
    @admin_episode.destroy
    respond_to do |format|
      format.html { redirect_to admin_episodes_url, notice: 'Admin episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_episode
      @admin_episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_episode_params
      params.require(:episode).permit(:number, :name, :air_date,
                                      :season_id, :description)
    end
end

app/helpers/admin_episodes_helper.rb
module AdminEpisodesHelper
end

app/views/admin_episodes/_form.html.erb
<%= form_for(@admin_episode, layout: :basic, url: {controller: 'admin_episodes', action: "#{@admin_episode.id ? 'update' : 'create'}"}) do |f| %>
  <% if @admin_episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_episode.errors.count, "error") %> prohibited this admin_episode from being saved:</h2>

      <ul>
      <% @admin_episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.number_field :number %>
    <%= f.text_field :name %>
    <%= f.select :season_id do %>
      <% Season.all.each do |s| %>
        <%= content_tag(:option, s.name, :value => s.id) %>
      <% end %>
    <% end %>
    <%= f.date_field :air_date %>
    <%= f.text_area :description %>
    <%= f.submit 'Update' %>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin_episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_episode %> |
<%= link_to 'Back', admin_episodes_path %>

app/views/admin_episodes/index.html.erb
<h1>Listing Episodes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_episodes.each do |admin_episode| %>
      <tr>
        <td><%= admin_episode.name %></td>
        <td><%= admin_episode.season.name %></td>
        <td><%= link_to 'Show', admin_episode %></td>
        <td><%= link_to 'Edit', edit_admin_episode_path(admin_episode) %></td>
        <td><%= link_to 'Destroy', admin_episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_admin_episode_path %>
<%= link_to 'Admin Home', admin_path %>

app/views/admin_episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_episodes_path %>

app/views/admin_episodes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_episode_path(@admin_episode) %> |
<%= link_to 'Back', admin_episodes_path %>