config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  get 'game_day', to: 'game_day#index', as: 'game_day'
  get 'drafts/:draft_id/picks', to: 'drafts#picks', as: 'draft_picks'
  get 'rules', to: 'rules#index', as: 'rules'
  get 'admin', to: 'admin#index', as: 'admin'

  get 'second_chance_votes/get_data', to: 'second_chance_votes#get_data',
      as: 'second_chance_votes_get_data'

  get 'second_chance_votes/results', to: 'second_chance_votes#results',
      as: 'second_chance_votes_results'

  resources :seasons, :episodes, :castaways, :drafts, :tribes, :users,
            :vote_outs, :second_chance_votes, :rule_articles, :admin_episodes,
            :admin_castaways, :admin_seasons, :admin_tribes

  resources :late_picks, only: %w(new create)

end

app/models/draft.rb
# == Schema Information
#
# Table name: drafts
#
#  id         :integer          not null, primary key
#  season_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  status     :string(255)      default("scheduled")
#
# Indexes
#
#  index_drafts_on_season_id  (season_id)
#

class Draft < ActiveRecord::Base
  belongs_to :season
  has_many :picks

  ROUND_TYPE = %w(cash drinking)
  STATUS = %w(scheduled started ended)

  def contestants
    picks.collect(&:contestant).uniq(&:id)
  end

  def players
    picks.collect(&:user).uniq(&:id)
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :authenticate_user!

  def index
    # most recently made Draft
    @current_draft = Draft.last
    # previous Draft
    @last_draft = Draft.first unless Draft.first == Draft.last
  end

  def new
  end

  def show
    @draft = Draft.find(params[:id])
  end

  def edit
    @draft = Draft.find(params[:id])
  end

  def create
    Draft.create!(draft_params)
    redirect_to drafts_path
  end

  def update
    @draft = Draft.find(params[:id])
    @draft.update! draft_params
    redirect_to drafts_path(@draft)
  end

  def picks
    @cash_picks = Pick.where(draft_id: params[:draft_id],
                             user_id: current_user.id, pick_type: "cash")
    @drinking_picks = Pick.where(draft_id: params[:draft_id],
                             user_id: current_user.id, pick_type: "drinking")
  end

  private

  def draft_params
    params.require(:draft).permit(:season_id)
  end
end

app/views/drafts/_draft_contestants_display.html.erb
<% contestants.each_with_index do |ct, i| %>
  <% if i > 0 %>
    <% panel_class = 'hidden character-info' %>
  <% else %>
    <% panel_class = 'character-info' %>
  <% end %>
  <%= panel class: panel_class, data: {id: ct.id} do %>
    <div class="row">
      <div class="col-xs-10 textfill">
        <span><%= ct.name %></span>
      </div>
      <div class="col-xs-2">
        <img src="<%= ct.picture_url %>" alt="" class="img-responsive"/>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <br class="visible-xs-block"/>
            <span class="btn btn-success center-block draft-contestant"
                  data-id="<%= ct.id %>" data-name="<%= ct.name %>">
              DRAFT
            </span>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  <% end %>
<% end %>

app/views/drafts/_draft_contestants_table.html.erb
<div class="row">
  <div class="col-xs-12 contestant-table">
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Tribe</th>
      </tr>
      </thead>
      <tbody>
      <% contestants.try(:each) do |c| %>
        <tr class="character-row" data-id="<%= c.id %>">
          <td><%= c.name %></td>
          <td><%= c.tribe_for_season(@draft.season_id) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/drafts/_ended_draft.html.erb
<% @draft.players.each do |p| %>
  <h3><%= p.name %></h3>
  <%= panel_row column_class: 'col-sm-6 col-xs-12' do %>
    <%= panel title: "Cash Picks", context: :info do %>
      <ul>
        <% p.cash_picks.each do |cp| %>
          <li>
            <%= link_to cp.contestant.name, contestant_path(cp.contestant) %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <%= panel title: 'Drinking Picks', context: :warning do %>
      <ul>
        <% p.drinking_picks.each do |dp| %>
          <li>
            <%= link_to dp.contestant.name, contestant_path(dp.contestant) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/drafts/edit.html.erb
<h1>
  Edit Draft - <%= @draft.season.name %>
</h1>
<hr/>
<%= form_for @draft, action: :update, layout: :basic do |f| %>
  <%= f.select :season_id, Season.all.collect {|p| [ p.name, p.id ] } %>
  <%= f.submit 'Save' %>
<% end %>

app/views/drafts/index.html.erb
<h1>
  Drafts
  <%= link_to 'New', new_draft_path,
              class: 'btn btn-sm btn-primary pull-right' if current_user.admin? %>
  <div class="clearfix"></div>
</h1>
<hr/>
<%= panel_row column_class: 'col-xs-12' do %>
  <% if @current_draft %>
    <%= panel heading: 'Current Draft', context: :success do %>
      <div class="container-fluid">
        <div class="col-xs-6">
          <h4>Season</h4>
          <p><%= @current_draft.season.name %></p>
        </div>
        <div class="col-xs-6">
          <h4>Contestants</h4>
          <% @current_draft.season.contestants.each do |c| %>
            <p><%= c.name %></p>
          <% end %>
        </div>
        <div class="col-xs-12">
            <%= link_to 'JOIN', draft_path(@current_draft.id), class: 'btn btn-lg btn-success center-block' %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if @last_draft %>
    <%= panel heading: 'Last Season', context: :warning do %>
      <div class="container-fluid">
        <div class="col-xs-6">
          <h4>Season</h4>
          <%= link_to @last_draft.season.name,
                      draft_path(@last_draft) %>
        </div>
        <div class="col-xs-6">
          <h4>Contestants</h4>
          <% @last_draft.season.contestants.each do |c| %>
            <p><%= c.name %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/drafts/new.html.erb
<h1>
  New Draft
</h1>
<hr/>
<%= form_for Draft.new, action: :create, layout: :basic do |f| %>
  <%= f.select :season_id, Season.all.collect {|p| [ p.name, p.id ] } %>
  <%= f.submit 'Save' %>
<% end %>

app/views/drafts/picks.html.erb
<%= panel_row column_class: 'col-sm-6 col-xs-12' do %>
  <%= panel title: 'Cash Picks', context: :info do %>
    <ul>
      <% @cash_picks.each do |cp| %>
        <li><%= link_to cp.castaway.name, castaway_path(cp.castaway) %></li>
      <% end %>
    </ul>
  <% end %>
  <%= panel title: 'Drinking Picks', context: :warning do %>
    <ul>
      <% @drinking_picks.each do |cp| %>
        <li><%= link_to cp.castaway.name, castaway_path(cp.castaway) %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/drafts/show.html.erb
<% season = @draft.try(:season) %>
<% contestants = season.try(:castaways) if season %>
<% users = User.all.sort %>
<% if @draft.status != 'ended' %>
  <%= content_for :body_id do 'draft' end %>
  <div class="row hidden" id="draft_container">
    <div class="col-xs-12 text-center">
        <h1>DO NOT REFRESH THIS PAGE, YOU WILL NOT BE ABLE TO GET BACK INTO THE DRAFT.</h1>
      <% if current_user.admin? %>
        <div class="btn btn-primary" id="start-draft">START DRAFT</div>
      <% end %>
    </div>
    <div class="col-sm-3 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <h2 class="textfill"><span>Time Left</span></h2>
          <h4 class="textfill">
            <span class="text-muted round-display"
                  data-round="1" data-round-type="Cash"></span>
          </h4>
          <p class="contestant-name text-success"><%= users.first.name %></p>
          <h3 class="textfill"><span class="countdown"></span></h3>
        </div>
      </div>
      <%= panel heading: 'Round 1 - Cash', context: :info, class: 'text-center contestants-panel' do %>
        <div class="panel-body"></div>
      <% end %>
    </div>
    <div class="col-sm-9 col-xs-12">
      <%= render 'draft_contestants_display',
                 contestants: contestants if contestants %>
      <%= render 'draft_contestants_table',
                 contestants: contestants if contestants %>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="hidden draft-id" data-id="<%= @draft.id %>"></div>
<% else %>
  <%= render 'drafts/ended_draft' %>
<% end %>